### ISSUE TITLE
Version in `About` tab is showing as `0.0.0.1`

### ISSUE THREAD

**Issue by der-eismann** [SneWs/tail-tray#17]
At the moment the version for the `About` tab is hardcoded to `0.0.0.1`:
https://github.com/SneWs/tail-tray/blob/master/src/MainWindow.ui#L1530

Would it possible to bump is as well on a new version? Or maybe even set the version on build?

**Comment by SneWs** [comment]
Hi, thanks for your report.
Yeah, we should probably set that on build instead and have that picked up :) 

I'll add it to my backlog.

Regards
// Grenis

**Comment by SneWs** [comment]
Ah, now I understand what version you mean, that's not for Tail Tray but rather the tailscale version running on your system. 

If I look at the about page on my end, it properly shows the tailscale client version, seems that perhaps your tailscale command isn't working as expected by Tail Tray or maybe it's not in your path, or, if you're not set as operator it can fail to invoke commands etc.

As it looks on my end:
![image](https://github.com/user-attachments/assets/d2526ac5-b658-4b5a-9604-11080b796f68)

Please verify that tailscale is on your path and that you're set as operator and we can take it from there

**Comment by SneWs** [comment]
Please sync and test building from the `develop` branch and verify that it works for you as well.

Regards
// Grenis
