### ISSUE TITLE
Last letter is missing for all clients

### ISSUE THREAD

**Issue by BeiNacht** [SneWs/tail-tray#20]
Hi, i getting for the clients not the complete names. That makes down the line issues like sending a file or using a exit node. I use a headscale server, maybe it has something to do with that problem.

![Screenshot_20241111_120904](https://github.com/user-attachments/assets/cf0e9445-410f-4851-9fd5-b009169ec7be)

Sending a file
`"error looking up IP of \"macboo\": lookup macboo on 100.100.100.100:53: no such host\n"`

Exit Node
`"invalid value \"min\" for --exit-node; must be IP or unique node name\n"`

**Comment by SneWs** [comment]
I think I found the problem, it's a bad boo boo with string manupulations for the host and magic dns domain name etc.

Please checkout the `develop` branch and build and run again, I think this solves your issue.

Regards
// Grenis

**Comment by BeiNacht** [comment]
this changes works fine

`"MagicDNSSuffix": "main.szczepan.ski",`
`"DNSName": "desktop.main.szczepan.ski",` 

i can create this week a PR for a nix package

**Comment by BeiNacht** [comment]
the same change you need to do for the exit nodes as well

**Comment by SneWs** [comment]
Alright, I think that would do it for this issue. Let me know otherwise.

Regards
// Grenis

**Comment by SneWs** [comment]
Fix merged to `master`
