### ISSUE TITLE
Packaging - AUR (Arch Linux)

### ISSUE THREAD

**Issue by HeavenVolkoff** [SneWs/tail-tray#24]
Hello,

First off, great project. I have been using it for the past few days and it works great.

I have created an AUR package for tail-tray to allow easy installation for Arch Linux users. I hope that is okay.

https://aur.archlinux.org/packages/tail-tray-git

**Comment by SneWs** [comment]
Great to hear that it works for you! 
And thank you for your efforts getting it setup in AUR! 🎉 

I'll add it to the getting started section as well.
